version: "3.7"

volumes:
  postgres: {}
  rabbitmq: {}

services:
  postgres:
    image: postgres:15.3-alpine3.18
    container_name: feeds-api-postgres
    restart: unless-stopped
    stop_signal: SIGINT
    environment:
      LC_ALL: "C.UTF-8"
      POSTGRES_DB: "feeds"
      POSTGRES_USER: "postgres"
      POSTGRES_PASSWORD: "${PG_PASSWD:-postgres}"
    ports:
    - "${PG_PORT:-5432}:5432"
    volumes:
    - "postgres:/var/lib/postgresql/data"

  rabbitmq:
    image: rabbitmq:3.12.2-management-alpine
    restart: unless-stopped
    environment:
      RABBITMQ_DEFAULT_USER: "admin"
      RABBITMQ_DEFAULT_PASS: "${RABBIT_PASSWD:-admin}"
    ports:
    - "${RABBIT_PORT:-5672}:5672"
    - "${RABBIT_MANAGEMENT_PORT:-15672}:15672"
    volumes:
    - "rabbitmq:/var/lib/rabbitmq"


networks:
  default:
    name: feeds
